before_install:
   - sudo apt-get update -qq
   - sudo apt-get install avahi-daemon libavahi-compat-libdnssd-dev
language: erlang
otp_release:
    - 17.5
    - 18.0
    - 18.1
script:
    - rebar compile
    - rebar skip_deps=true ct
